spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger